"""
Generate Report — Generates a markdown summary of today's job hunt.
"""

from __future__ import annotations

import asyncio
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import structlog
from app.database.engine import AsyncSessionLocal
from app.database.repositories.ai_analysis_repository import AIAnalysisRepository
from app.database.repositories.job_repository import JobRepository
from app.scraper.output_writer import OutputWriter
from app.utils.logging import configure_logging

logger = structlog.get_logger(__name__)


async def main() -> None:
    configure_logging()
    writer = OutputWriter()
    today = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    async with AsyncSessionLocal() as session:
        job_repo = JobRepository(session)
        ai_repo = AIAnalysisRepository(session)

        total_jobs = await job_repo.count()
        top_matches = await ai_repo.get_top_matches(min_score=80.0, limit=10)
        distribution = await ai_repo.get_score_distribution()

    lines = [
        f"# 🎯 Ultimate Job Hunting ATS — Daily Report",
        f"**Date:** {today}",
        f"**Candidate:** Dhany Arya Pratama",
        "",
        "---",
        "",
        "## 📊 Summary",
        f"- **Total Jobs in DB:** {total_jobs}",
        f"- **Elite Matches (90+):** {distribution.get('90-100', 0)}",
        f"- **Strong Matches (80-89):** {distribution.get('80-89', 0)}",
        f"- **Good Matches (70-79):** {distribution.get('70-79', 0)}",
        "",
        "---",
        "",
        "## 🚀 Top Matches Today",
        "",
    ]

    for match in top_matches:
        lines.append(f"- **Score {match.match_score:.0f}/100** — {match.job_category} | {match.prediction_market}")

    lines += ["", "---", "", "*Generated by Ultimate Job Hunting ATS*"]

    report = "\n".join(lines)
    writer.write_report(report, f"daily_report_{today}")
    logger.info("Report generated", date=today)


if __name__ == "__main__":
    asyncio.run(main())
